[package]
name = "acos5_pkcs15"
version = "0.0.30"
authors = ["carblue <bluecars@posteo.eu>"]
edition = "2018"

[dependencies]
libc = "0.2"
cfg-if = "1.0"
opensc-sys = { path = "../opensc-sys" }

[lib]
name = "acos5_pkcs15"
crate-type = ["cdylib"]
