language: rust
rust:
  - stable

sudo: required
dist: xenial

before_install:
  - sudo add-apt-repository -y -u ppa:gertvdijk/opensc-backports
  - sudo apt-get install -y opensc opensc-pkcs11
  - ls -lh /usr/lib/x86_64-linux-gnu/libopensc*
  - sudo ln -s -T /usr/lib/x86_64-linux-gnu/libopensc.so.5 /usr/lib/x86_64-linux-gnu/libopensc.so
  - sudo ldconfig
  - sudo cp travis/opensc.pc /usr/lib/x86_64-linux-gnu/pkgconfig
  - travis/check_opensc.sh
