language: d

# latest dmd, gdc and ldc
# ldc fails; ldc built with cmake -DBUILD_SHARED_LIBS=ON ? if yes, ld doesn't find them or names are wrong; "dflags-posix-ldc": ["-defaultlib=:libphobos2-ldc.so,:libdruntime-ldc.so"]
# gdc fails; gdc built with --enable-shared ?
# Running ./lib/acos5_64-test-library 
# ./lib/acos5_64-test-library: error while loading shared libraries: libgphobos.so.68: cannot open shared object file: No such file or directory
# Program exited with code 127
# Both ldc and gdc seem to be built without shared libs phobos/druntime

d:
  - dmd

dist: trusty
sudo: required

# opensc-pkcs11 is required for libopensc.so(.*), opensc seems to be optional if no tools/opensc.conf/profile used
before_install:
  - sudo add-apt-repository -y ppa:gertvdijk/opensc-backports
  - sudo apt-get update -y -qq
  - sudo apt-get install -y opensc-pkcs11 opensc
  - sudo ln -s -T /usr/lib/x86_64-linux-gnu/libopensc.so.4.0.0 /usr/lib/libopensc.so
  - sudo ldconfig
# install from source:
#before_install:
#  - sudo apt-get install -y pcscd libccid libpcsclite-dev libssl-dev libltdl-dev libreadline-dev autoconf automake build-essential docbook-xsl xsltproc libtool pkg-config openssl
#install:
#  - wget https://sourceforge.net/projects/opensc/files/OpenSC/opensc-0.16.0/opensc-0.16.0.tar.gz
#  - tar -xzvf opensc-0.16.0.tar.gz
#  - pushd opensc-0.16.0 && ./bootstrap && ./configure --prefix=/usr --sysconfdir=/etc/opensc && make && sudo make install && popd
#  - sudo ldconfig
script:
  - dub test  --compiler=$DC
  - dub build --compiler=$DC --build=release
  - sudo patch -u -b /etc/opensc/opensc.conf config/patchfile_travis.diff
#  - cat /etc/opensc/opensc.conf
  - find . -name libacos5_64.so
  - ls -la
  - opensc-tool -D
  - cat /tmp/opensc-debug.log
