language: rust
rust:
  - stable

sudo: required
dist: bionic  # see https://docs.travis-ci.com/user/reference/bionic/

before_install:
  - sudo apt-get install -y opensc opensc-pkcs11 # bionic supplies OpenSC version 0.17.0; current is version 0.19.0
  - ls -lh /usr/lib/x86_64-linux-gnu/libopensc*
  - sudo ln -s -T /usr/lib/x86_64-linux-gnu/libopensc.so.5 /usr/lib/x86_64-linux-gnu/libopensc.so
  - ls -lh /usr/lib/x86_64-linux-gnu/libopensc*
  - ls -lh /usr/lib/x86_64-linux-gnu/pkgconfig/opensc*
  - sudo cp /usr/lib/x86_64-linux-gnu/pkgconfig/opensc-pkcs11.pc /usr/lib/x86_64-linux-gnu/pkgconfig/opensc.pc
  - sudo sed -i 's/lopensc-pkcs11/lopensc/g' /usr/lib/x86_64-linux-gnu/pkgconfig/opensc.pc
  - sudo sed -i 's/PKCS#11 module/library/g' /usr/lib/x86_64-linux-gnu/pkgconfig/opensc.pc
  - sudo ldconfig
  - cat /usr/lib/x86_64-linux-gnu/pkgconfig/opensc.pc
  - opensc-tool -i
