language: d

# latest dmd, gdc and ldc
d:
  - dmd
#  - ldc

dist: trusty
sudo: required
before_install:
  - sudo apt-get install -y pkg-config openssl libssl-dev libpcsclite-dev libltdl-dev libreadline-dev
install:
  - wget https://sourceforge.net/projects/opensc/files/OpenSC/opensc-0.16.0/opensc-0.16.0.tar.gz
  - tar -xzvf opensc-0.16.0.tar.gz
  - pushd opensc-0.16.0 && ./configure --prefix=/usr --sysconfdir=/etc/opensc && make && sudo make install && popd
  - sudo ldconfig
script:
  - dub test --compiler=$DC
#ls -la
#dub build --compiler=$DC --build=release
#sudo ldconfig
#sudo patch -u -b /etc/opensc/opensc.conf config/patchfile_travis.diff
#cat /etc/opensc/opensc.conf
#opensc-tool -D