language: d

# latest dmd, ldc, gdc working on my own box; with travis, dmd build only succeeds:
# ldc fails; ldc built with cmake -DBUILD_SHARED_LIBS=ON ? if yes, ld doesn't find them or names are different;  "dflags-posix-ldc": ["-defaultlib=:libphobos2-ldc.so,:libdruntime-ldc.so"]
# gdc fails; gdc built with --enable-shared ?  "dflags-posix-gdc": ["-shared-libphobos"]
# gdc: Running ./lib/acos5_64-test-library
# ./lib/acos5_64-test-library: error while loading shared libraries: libgphobos.so.68: cannot open shared object file: No such file or directory
# Program exited with code 127
# Both ldc and gdc seem to be built without shared libs phobos/druntime

d:
  - dmd

dist: trusty
sudo: required

# opensc-pkcs11 is required for libopensc.so(.*), opensc required for opensc-tool and /etc/opensc/opensc.conf
# the ppa used is v0.16.0 backported (16.04, 14.10, 14.04, 12.04), but missing a link for libopensc.so
before_install:
  - sudo add-apt-repository -y ppa:gertvdijk/opensc-backports
  - sudo apt-get update -y -qq
  - sudo apt-get install -y -qq opensc-pkcs11 opensc
  - sudo ln -s -T /usr/lib/x86_64-linux-gnu/libopensc.so.4.0.0 /usr/lib/libopensc.so
#  - sudo ldconfig
# want to build/install opensc from source, possibly patching opensc source code:
# https://github.com/OpenSC/OpenSC/wiki/Compiling-and-Installing-OpenSC-on-Unix-flavors
#before_install:
#  - sudo apt-get install -y pcscd libccid libpcsclite-dev libssl-dev libltdl-dev libreadline-dev autoconf automake build-essential docbook-xsl xsltproc libtool pkg-config openssl
#install:
#  - wget https://sourceforge.net/projects/opensc/files/OpenSC/opensc-0.16.0/opensc-0.16.0.tar.gz
#  - tar -xzvf opensc-0.16.0.tar.gz
#  - pushd opensc-0.16.0 && ./bootstrap && ./configure --prefix=/usr --sysconfdir=/etc/opensc && make && sudo make install && popd
#  - sudo ldconfig
script:
  - dub test  --compiler=$DC
  - dub build --compiler=$DC --build=release
  - sudo cp lib/libacos5_64.so /usr/lib
  - sudo ldconfig
#  - echo $TRAVIS_BUILD_DIR   /home/travis/build/carblue/acos5_64
#  - ls -la $TRAVIS_BUILD_DIR   got all my repo files/dirs in here as expected, but nevertheless this didn't work with travis so far: module = $TRAVIS_BUILD_DIR/lib/libacos5_64.so 
  - ls -la ${TRAVIS_BUILD_DIR}/lib
  - sudo patch -u -b /etc/opensc/opensc.conf config/patchfile_travis.diff
  - diff /etc/opensc/opensc.conf.orig /etc/opensc/opensc.conf || true
#  - cat /etc/opensc/opensc.conf
  - opensc-tool -D
# should result in:
#Configured card drivers:
#  acos5_64         ACS ACOS5-64 (v2.00: Smart Card/CryptoMate64)
#  default          Default driver for unknown cards
#  - cat /tmp/opensc-debug.log
