language: d

d:
  - dmd

dist: trusty
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:gertvdijk/opensc-backports
  - sudo apt-get update -y -qq
  - sudo apt-get install -y -qq opensc-pkcs11 opensc
  - sudo ln -s -T /usr/lib/x86_64-linux-gnu/libopensc.so.4.0.0 /usr/lib/libopensc.so

script:
  - dub build --build=release --compiler=$DC
  - sudo cp lib/libacos5_64.so /usr/lib
  - sudo ldconfig
  - sudo patch -u -b /etc/opensc/opensc.conf config/etc_opensc_opensc_conf.patch || cat /etc/opensc/opensc.conf.rej
  - diff /etc/opensc/opensc.conf.orig /etc/opensc/opensc.conf || true
  - opensc-tool -D
  - dub test  --compiler=$DC
