platform: x64
environment:
 matrix:
  - DC: dmd
    DVersion: 2.073.0
    arch: x86

skip_tags: false
branches:
  only:
    - master

install:
  - ps: function SetUpDCompiler
        {
            if($env:DC -eq "dmd"){
              if($env:arch -eq "x86"){
                $env:DConf = "m32";
              }
              elseif($env:arch -eq "x64"){
                $env:DConf = "m64";
              }
              echo "downloading ...";
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "http://downloads.dlang.org/releases/2.x/$($version)/dmd.$($version).windows.7z" -OutFile "c:\dmd.7z";
              echo "finished.";
              pushd c:\\;
              7z x dmd.7z > $null;
              popd;
            }
            elseif($env:DC -eq "ldc"){
              echo "downloading ...";
              if($env:arch -eq "x86"){
                $env:DConf = "m32";
              }
              elseif($env:arch -eq "x64"){
                $env:DConf = "m64";
              }
              $env:toolchain = "msvc";
              $version = $env:DVersion;
              Invoke-WebRequest "https://github.com/ldc-developers/ldc/releases/download/v$($version)/ldc2-$($version)-win64-msvc.zip" -OutFile "c:\ldc.zip";
              echo "finished.";
              pushd c:\\;
              7z x ldc.zip > $null;
              popd;
            }
        }
  - ps: function SetUpACSpcsc
        {
           echo "downloading ...";
           Invoke-WebRequest "http://www.acs.com.hk/download-driver-unified/8244/ACS-Unified-MSI-Winx64-4220.zip" -OutFile "c:\ACSpcsc.zip";
           echo "finished.";
           pushd c:\\;
           7z x ACSpcsc.zip -oACSpcsc > $null;
           ACSpcsc\\Setup.exe /norestart;
           popd;
        }
  - ps: function SetUpOpenSC
        {
           echo "downloading ...";
           Invoke-WebRequest "https://sourceforge.net/projects/opensc/files/OpenSC/opensc-0.16.0/OpenSC-0.16.0-win32_vs12-Release.msi/download" -OutFile "C:\OpenSC1632.msi";
           echo "finished.";
           pushd c:\\;
           msiexec /i OpenSC1632.msi /qn /norestart;
           popd;
        }
  - ps: SetUpDCompiler
  - ps: SetUpACSpcsc
  - ps: SetUpOpenSC
  - ps: $env:PATH += ";C:\OpenSSL-Win32\bin;C:\Program Files (x86)\OpenSC Project\OpenSC\tools;C:\projects\acos5-64\lib;C:\projects\acos5_64\lib";
  - cinst dub
  - dub --version

before_build:
  - ps: if($env:arch -eq "x86"){
            $env:compilersetupargs = "x86";
            $env:Darch = "x86";
          }
        elseif($env:arch -eq "x64"){
            $env:compilersetupargs = "amd64";
            $env:Darch = "x86_64";
        }
  - ps : if($env:DC -eq "dmd"){
           $env:PATH += ";C:\dmd2\windows\bin;";
         }
         elseif($env:DC -eq "ldc"){
           $version = $env:DVersion;
           $env:PATH += ";C:\ldc2-$($version)-win64-msvc\bin";
           $env:DC = "ldc2";
         }
  - ps: $env:compilersetup = "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall";
  - '"%compilersetup%" %compilersetupargs%'

build_script:
 - echo dummy build script - don't remove me

test_script:
 - echo %PLATFORM%
 - echo %Darch%
 - echo %DC%
 - echo %PATH%
 - '%DC% --version'
 - dub build --arch=%Darch% --compiler=%DC%
# - opensc-tool -D
