[package]
name = "acos5"
version = "0.0.30"
authors = ["carblue <bluecars@posteo.eu>"]
edition = "2018"

[dependencies]
libc = "0.2"
num-integer = "0.1"
cfg-if = "1.0"
#function_name = "0.2"
opensc-sys = { path = "../opensc-sys" }

[lib]
name = "acos5"
crate-type = ["cdylib"]
