[package]
name = "acos5"
version = "0.0.30"
authors = ["Carsten Blüggel, carblue <bluecars@posteo.eu>"]
edition = "2021"

[dependencies]
libc = "0.2"
cfg-if = "1.0"
opensc-sys = { path = "../opensc-sys" }
num-integer = "0.1"
#function_name = "0.2"

[lib]
name = "acos5"
crate-type = ["cdylib"]
