[package]
name = "project_pkcs11_example_apps"
version = "0.0.30"
authors = ["Carsten Blüggel <bluecars@posteo.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pkcs11 = "0.5"
