[package]
name = "opensc-sys"
links = "opensc"
version = "0.0.30"
authors = ["carblue <bluecars@posteo.eu>"]
edition = "2018"

[dependencies]
libc = "0.2"
cfg-if = "1.0"

[build-dependencies]
libloading = "0.6"
